### ISSUE TITLE
Develop hardware setup documentation and/or bash install script

### ISSUE THREAD

**Issue by Albert221** [PozytywneInicjatywy/dashboard-front#18]
To make setup of frontend on Raspberry Pi Zero W faster and more convenient, develop a documentation saying how to deploy the frontend step-by-step with things including:

- Setting the timezone
- Connecting to WiFi network
- Adding CRON job for auto updating
- Adding `~/.config/lxsession/LXDE-pi/autostart` record for autostarting browser on HW's startup

**Comment by JakubBizewski** [comment]
The documentation is done, you can access it at https://github.com/PozytywneInicjatywy/dashboard-front/wiki/Hardware-setup.
