### ISSUE TITLE
Lucky numbers tile

### ISSUE THREAD

**Issue by Albert221** [PozytywneInicjatywy/dashboard-front#2]
![image](https://user-images.githubusercontent.com/4085280/32406529-776ef4b4-c17a-11e7-8fb1-4b8764365c2f.png)
## Missing features

- [x] Determine a way how to generate these numbers exactly the same on any device:
    - Use random generator with seed being the current date
    - Generate it on the backend and fetch it once a day

**Comment by JakubBizewski** [comment]
Generating the lucky numbers on the backend and fetching them to clients would be more appropriate. In this way we can make sure that they are really consistent across all devices.

**Comment by Albert221** [comment]
Backend done by PozytywneInicjatywy/dashboard-back@538f9877d91ee35f599c53b87dc57a6ad79b9315

**Comment by JakubBizewski** [comment]
Pull request sent #6

**Comment by JakubBizewski** [comment]
Implemented as of 99ea4846d8d9b013af973a83152ee503906c8393
