### ISSUE TITLE
Timetable tile

### ISSUE THREAD

**Issue by Albert221** [PozytywneInicjatywy/dashboard-front#4]
![image](https://user-images.githubusercontent.com/4085280/32406615-dee6cddc-c17b-11e7-87d5-ca5e936b7436.png)

## Missing features

- [x] Fetch timetables from the backend.
- [ ] Animate rows on update.

**Comment by JakubBizewski** [comment]
The timetables are now fetched from the backend as of fcd8030822a6b186f2a0d3c701245a0f4ec35143
Now I need to reduce visible lessons in some reasonable fashion.

**Comment by JakubBizewski** [comment]
Visible lessons are now limited to 3 per class as of 2e1f92d1aef343596f8781a59a053c3f2ede7434.

**Comment by JakubBizewski** [comment]
Pull request #12 created.
