### ISSUE TITLE
Create Background component and remove TwitchTile

### ISSUE THREAD

**Issue by Albert221** [PozytywneInicjatywy/dashboard-front#7]
Create Background component which will serve as a background for whole dashboard. It would have likely two props:
- `type` for type of background, now I see `"image"` and `"twitch"` so that in different dashboards (in different school buildings) would be different backgrounds
- `src` which will vary depending on `type`, i.e. URL for `"image"` and Twitch channel name for `"twitch"`

After that, remove TwitchTile because it won't be needed anymore.

**Comment by lukasz-ciskowski** [comment]
Pull request sent [#11](https://github.com/PozytywneInicjatywy/dashboard-front/pull/11)

**Comment by Albert221** [comment]
Closing as #11 is merged.
